c_stdlib_version:              # [osx and x86_64]
  - 10.14                      # [osx and x86_64]
# Until we can fix the problem with R 4.4.3 on osx-64,
# build with R 4.4.2
# https://github.com/conda-forge/r-tiledb-feedstock/pull/97
r_base:                        # [osx and x86_64]
  - 4.3                        # [osx and x86_64]
  - 4.4.2                      # [osx and x86_64]
