{% set name = "r-tiledb" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-R/archive/{{ version }}.tar.gz
  sha256: 1310459f518d521a2488f93f328cbe7de02dd5e211a356548bb7216a6e52c597
  patches:   # [osx and not arm64]
    - 0001-skip-osx-test-to-avoid-spurious-segfault.patch  # [osx and not arm64]

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - make
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-nanotime  # [build_platform != target_platform]
    - r-rcpp >=1.0.8  # [build_platform != target_platform]
    - r-rcppspdlog  # [build_platform != target_platform]
  host:
    - r-base
    - tiledb 2.14.*
    - r-rcpp >=1.0.8
    - r-rcppspdlog
    - r-nanotime
    - r-spdl
  run:
    - r-base
    - r-nanotime
    - tiledb 2.14.*
    - r-spdl

test:
  requires:
    - r-tinytest
    - r-nycflights13
    - r-palmerpenguins
  commands:
    - Rscript -e 'tinytest::test_package("tiledb")'

about:
  home: https://www.tiledb.com
  license: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  summary: R interface to the TileDB array storage manager

  description: |
    TileDB is a highly-parallelized, cloud native array storage engine.
  doc_url: https://docs.tiledb.com/developer/
  dev_url: https://github.com/TileDB-Inc/TileDB-R

extra:
  recipe-maintainers:
    - ihnorton
    - Shelnutt2
    - eddelbuettel
    - jdblischak
