{% set name = "r-tiledb" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-R/archive/{{ version }}.tar.gz
  sha256: 4a5d41491e9ca010956b3480eca60339ba8cdfc5f376296e544f626036476f10

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  ignore_run_exports: # ignore here to avoid overlink warning b/c test require doesn't work
    - r-testthat

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - make
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-sys                      # [build_platform != target_platform]
    - r-nanotime  # [build_platform != target_platform]
    - r-rcpp >=0.12.15  # [build_platform != target_platform]
  host:
    - r-base
    - tiledb 2.8.*
    - r-rcpp >=0.12.15
    - r-testthat
    - r-nanotime
  run:
    - r-base
    - r-nanotime
    - tiledb 2.8.*

test:
  requires:
    - r-tinytest
    - r-nycflights13
    - r-palmerpenguins
  commands:
    - Rscript -e 'tinytest::test_package("tiledb")'

about:
  home: https://www.tiledb.com
  license: MIT
  license_file: LICENSE
  summary: R interface to the TileDB array storage manager

  description: |
    TileDB is a highly-parallelized, cloud native array storage engine.
  doc_url: https://docs.tiledb.com/developer/
  dev_url: https://github.com/TileDB-Inc/TileDB-R

extra:
  recipe-maintainers:
    - ihnorton
    - Shelnutt2
    - eddelbuettel
