{% set name = "r-tiledb" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-R/archive/{{ version }}.tar.gz
  sha256: f75157d0ff6b18a9d42f17419b35b8916238d9bd4bba2b76d269068c452cd92a

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  ignore_run_exports: # ignore here to avoid overlink warning b/c test require doesn't work
    - r-testthat

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - r-base
    - tiledb >2.0
    - r-rcpp >=0.12.15
    - r-testthat
    - r-nanotime
    - r-arrow
  run:
    - r-base
    - r-nanotime
    - r-rcpp >=0.12.15
    - r-arrow

test:
  requires:
    - r-tinytest
  commands:
    - Rscript -e 'tinytest::test_package("tiledb")'

about:
  home: https://www.tiledb.com
  license: MIT
  license_file: LICENSE
  summary: R interface to the TileDB array storage manager

  description: |
    TileDB is a highly-parallelized, cloud native array storage engine.
  doc_url: https://docs.tiledb.com/developer/
  dev_url: https://github.com/TileDB-Inc/TileDB-R

extra:
  recipe-maintainers:
    - ihnorton
    - Shelnutt2
    - eddelbuettel
