{% set name = "r-tiledb" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-R/archive/{{ version }}.tar.gz
  sha256: 2f00e45a2df952d722e287f81c8d3f449a92bf4871cded1d180497f0397b50c3

build:
  number: 1
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  ignore_run_exports: # ignore here to avoid overlink warning b/c test require doesn't work
    - r-testthat

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - r-base
    - tiledb >2.0
    - r-rcpp >=0.12.15
    - r-testthat
    - r-nanotime
  run:
    - r-base
    - r-nanotime
    - r-rcpp >=0.12.15

test:
  requires:
    - r-tinytest
  commands:
    - Rscript -e 'tinytest::test_package("tiledb")'

about:
  home: https://www.tiledb.com
  license: MIT
  license_file: LICENSE
  summary: R interface to the TileDB array storage manager

  description: |
    TileDB is a highly-parallelized, cloud native array storage engine.
  doc_url: https://docs.tiledb.com/developer/
  dev_url: https://github.com/TileDB-Inc/TileDB-R

extra:
  recipe-maintainers:
    - ihnorton
    - Shelnutt2
    - eddelbuettel
