{% set name = "r-tiledb" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/TileDB-R/archive/{{ version }}.tar.gz
  sha256: b900f5162e859b6f8339d34a276d0b8463e9b394aeb62e088e4baae4219a7233

build:
  number: 1
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/
  ignore_run_exports: # ignore here to avoid overlink warning b/c test require doesn't work
    - r-testthat

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - make
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-sys                      # [build_platform != target_platform]
    - r-nanotime  # [build_platform != target_platform]
    - r-rcpp >=0.12.15  # [build_platform != target_platform]
  host:
    - r-base
    - tiledb >2.0
    - r-rcpp >=0.12.15
    - r-testthat
    - r-nanotime
    - r-arrow
  run:
    - r-base
    - r-nanotime
    - r-arrow

test:
  requires:
    - r-tinytest
  commands:
    - Rscript -e 'tinytest::test_package("tiledb")'

about:
  home: https://www.tiledb.com
  license: MIT
  license_file: LICENSE
  summary: R interface to the TileDB array storage manager

  description: |
    TileDB is a highly-parallelized, cloud native array storage engine.
  doc_url: https://docs.tiledb.com/developer/
  dev_url: https://github.com/TileDB-Inc/TileDB-R

extra:
  recipe-maintainers:
    - ihnorton
    - Shelnutt2
    - eddelbuettel
